# syntax=docker/dockerfile:1

FROM node:22-alpine AS builder

WORKDIR /app

COPY main_interface/package*.json ./

RUN npm ci

COPY main_interface/ .

ARG VITE_API_BASE_URL
ARG VITE_API_BASE_URL_PREDICTIVE

ENV VITE_API_BASE_URL=$VITE_API_BASE_URL
ENV VITE_API_BASE_URL_PREDICTIVE=$VITE_API_BASE_URL_PREDICTIVE

RUN npm run build

# =========================
# Stage 2 : Nginx
# =========================

FROM nginx:alpine

RUN rm /etc/nginx/conf.d/default.conf

COPY main_interface/nginx.conf /etc/nginx/conf.d/default.conf

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]