"""
Django settings for main_pro project.

Generated by 'django-admin startproject' using Django 4.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
#Maintenant je suis en mode développeur - FUTURE : - Mode Production
from pathlib import Path
import os


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DI = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
from datetime import timedelta

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
REMOVED_SECRET_LINE

#SEKRET KEY crée avec powershell - utilisé par Django - à mettre dans .env pour la sercurité

#On va utilser GIT pour assurer la securité et que la clé ne sera pas partagé en production 
#SECRET_KEY = "REMOVED_SECRET"
TRAIN_API_TOKEN = "260fb4baef0f1c2cd397fa9301212bfa7f3e4caf"
# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True
SESSION_COOKIE_SAMESITE = None
SESSION_COOKIE_SECURE = False
CSRF_COOKIE_SECURE = False
CSRF_COOKIE_SAMESITE = False
"""
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '192.168.8.100', 'introductory-juttingly-viola.ngrok-free.dev']
"""
ALLOWED_HOSTS = ['localhost', '127.0.0.1', '10.173.125.85', '10.112.219.85']

# j'utilise des cookies/sessions = True
CORS_ALLOW_ALL_ORIGINS = False  # Très important pour le test == True
CORS_ALLOW_CREDENTIALS = False
SECURE_CROSS_ORIGIN_OPENER_POLICY = None # Aide parfois pour les flux video



MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

SECRET_KEY = os.getenv("SECRET_KEY")
if not SECRET_KEY:
    raise RuntimeError("SECRET_KEY n'est pas configurée")
#AUTH_USER_MODEL = "users.CustomUser"

# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    'rest_framework',
    'rest_framework.authtoken',
    'rest_framework_simplejwt',
    'channels',
    'corsheaders',
    'maintenance',
    'predictive',
    'django_extensions',
]

# utilisation de la technique Abstract User
AUTH_USER_MODEL = 'maintenance.Utilisateur'

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],

   
    #'DEFAULT_THROTTLE_CLASSES': [
        #'rest_framework.throttling.AnonRateThrottle', # Pour les utilisateurs non connectés
    #],
    'DEFAULT_THROTTLE_RATES': {
        'anon': '5/minute', # Maximum 5 tentatives par minute et par adresse IP
        'password_reset': '3/minute',
    }
}



SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=60),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
    "AUTH_HEADER_TYPES": ("Bearer",),
}

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

# port par défaut de Vite 5173
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://10.178.18.85:3000",
    "http://192.168.12.85:3000",
    "http://localhost:5173",
    "http://10.173.125.85:5173",
    'https://introductory-juttingly-viola.ngrok-free.dev', #ngrok url : probleme d_exposition = basculer vers posrt 3000-8000
]



CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:8000",
    "https://*.trycloudflare.com",
]


ROOT_URLCONF = "main_pro.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [os.path.join(BASE_DI, "templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "main_pro.wsgi.application"

ASGI_APPLICATION = "main_pro.asgi.application"

# Exemple de backend mémoire (à adapter si Redis)
CHANNEL_LAYERS = {
    "default": {
        "BACKEND": "channels.layers.InMemoryChannelLayer",
    },
}

"""
CHANNEL_LAYERS = {
    "default": {

        "BACKEND": "channels_redis.core.RedisChannelLayer",
        "CONFIG": {"hosts": [("127.0.0.1", 6379)]}, # si Redis tourne en local
    },
}
"""
# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'base_main',
        'USER': 'sabri_main',
        'PASSWORD': 'REMOVED_SECRET',
        'HOST': 'localhost',
        'PORT': '5432',
    }
}
"""
#on modifie host=localhost pour docker
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'main',
        'USER': 'sabri_main',
        'PASSWORD': 'REMOVED_SECRET',
        'HOST': 'postgres',
        'PORT': '5432',
    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = "static/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'djemaisabri90@gmail.com'
EMAIL_HOST_PASSWORD = 'REMOVED_SECRET'
DEFAULT_FROM_EMAIL = 'djemaisabri90@gmail.com'
