# Generated by Django 4.2.7 on 2026-04-13 11:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainingLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("trained_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("dataset_size", models.IntegerField()),
                ("class_distribution", models.JSONField()),
                ("accuracy", models.FloatField()),
                ("precision", models.FloatField()),
                ("recall", models.FloatField()),
                ("f1_score", models.FloatField()),
            ],
        ),
    ]
