# Generated by Django 4.2.7 on 2026-04-13 11:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("predictive", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="model_version",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="traininglog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="training_logs",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="traininglog",
            name="trained_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
    ]
