# Generated by Django 4.2.7 on 2026-04-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictive", "0002_traininglog_model_version_traininglog_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="success",
            field=models.BooleanField(default=True),
        ),
    ]
