# Generated by Django 4.2.7 on 2026-04-19 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictive", "0003_traininglog_success"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="validation_metrics",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
