# Generated by Django 4.2.7 on 2026-04-24 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictive", "0004_traininglog_validation_metrics"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="balanced_accuracy",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="traininglog",
            name="confusion_matrix",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="traininglog",
            name="macro_f1",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
