# Generated by Django 4.2.7 on 2026-04-24 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictive", "0005_traininglog_balanced_accuracy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="minority_ratio",
            field=models.FloatField(default=0.2),
        ),
    ]
