# Generated by Django 4.2.7 on 2026-04-25 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictive", "0006_traininglog_minority_ratio"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="hyperparameters",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
