# Generated by Django 4.2.7 on 2026-04-25 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("predictive", "0007_traininglog_hyperparameters"),
    ]

    operations = [
        migrations.AddField(
            model_name="traininglog",
            name="balanced_distribution",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
