# Generated by Django 4.2.7 on 2026-04-12 21:07

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="Utilisateur",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="email address"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("technicien", "Technicien"),
                            ("expert", "Expert"),
                            ("operateur", "Operateur"),
                        ],
                        default="technicien",
                        max_length=20,
                    ),
                ),
                ("telephone", models.CharField(blank=True, max_length=20, null=True)),
                ("must_change_password", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom",
                    models.CharField(
                        choices=[
                            ("electrique", "Électrique"),
                            ("mecanique", "Mécanique"),
                            ("automation", "Automation"),
                            ("utilitaire", "Utilitaire"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Intervention",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_debut", models.DateTimeField(blank=True, null=True)),
                ("date_fin", models.DateTimeField(blank=True, null=True)),
                ("actions_realisees", models.TextField(blank=True)),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("basse", "Basse"),
                            ("moyenne", "Moyenne"),
                            ("haute", "Haute"),
                        ],
                        default="moyenne",
                        max_length=10,
                    ),
                ),
                (
                    "type_intervention",
                    models.CharField(
                        choices=[
                            ("corrective", "Corrective"),
                            ("preventive", "Préventive"),
                            ("inspection", "Inspection"),
                        ],
                        default="inspection",
                        max_length=20,
                    ),
                ),
                ("date_validation", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_locked", models.BooleanField(default=False)),
                (
                    "techniciens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="interventions_techniciens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "valide_par",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="interventions_validees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Machine",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "localisation",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                ("type", models.CharField(blank=True, max_length=100, null=True)),
                ("date_installation", models.DateField(blank=True, null=True)),
                (
                    "etat",
                    models.CharField(
                        choices=[
                            ("SERVICE", "En service"),
                            ("PANNE", "En panne"),
                            ("MAINTENANCE", "En maintenance"),
                            ("INCONNU", "Inconnu"),
                        ],
                        default="SERVICE",
                        max_length=50,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Piece",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("reference", models.CharField(max_length=100, unique=True)),
                ("stock_disponible", models.PositiveIntegerField(default=0)),
                ("fournisseur", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="Signalement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("nouveau", "Nouveau"),
                            ("en_cours", "En cours"),
                            ("traite", "Traité"),
                            ("clos", "Clos"),
                        ],
                        db_index=True,
                        default="nouveau",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manuel", "Humain"),
                            ("preventif", "Préventif"),
                            ("iot", "IoT"),
                        ],
                        db_index=True,
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "cree_par",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.machine",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="WorkOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("corrective", "Corrective"),
                            ("preventive", "Préventive"),
                            ("predictive", "Prédictive"),
                        ],
                        default="predictive",
                        max_length=50,
                    ),
                ),
                (
                    "priorite",
                    models.CharField(
                        choices=[
                            ("high", "Haute"),
                            ("medium", "Moyenne"),
                            ("low", "Basse"),
                        ],
                        default="high",
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "date_creation",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                ("date_cloture", models.DateTimeField(blank=True, null=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="workorders",
                        to="maintenance.categorie",
                    ),
                ),
                (
                    "cree_par",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_crees",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "expert",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bons_expert",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.machine",
                    ),
                ),
                (
                    "signalement",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.signalement",
                    ),
                ),
                (
                    "techniciens",
                    models.ManyToManyField(
                        blank=True,
                        related_name="bons_techniciens",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Rapport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contenu", models.TextField()),
                (
                    "fichier_pdf",
                    models.FileField(blank=True, null=True, upload_to="rapports/"),
                ),
                ("date_generation", models.DateTimeField(auto_now_add=True)),
                (
                    "workorder",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.workorder",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PieceUtilisee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantite", models.PositiveIntegerField()),
                (
                    "intervention",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pieces",
                        to="maintenance.intervention",
                    ),
                ),
                (
                    "piece",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="maintenance.piece",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("workorder_created", "WorkOrder créé"),
                            ("intervention_started", "Intervention démarrée"),
                            ("intervention_finished", "Intervention terminée"),
                            ("intervention_validated", "Intervention validée"),
                        ],
                        db_index=True,
                        default="workorder_created",
                        max_length=50,
                    ),
                ),
                ("url", models.CharField(blank=True, max_length=255, null=True)),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "categorie",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="maintenance.categorie",
                    ),
                ),
                (
                    "intervention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notifications",
                        to="maintenance.intervention",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="maintenance.workorder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Création"),
                            ("update", "Mise à jour"),
                            ("delete", "Suppression"),
                            ("start", "Démarrage"),
                            ("finish", "Clôture"),
                            ("validate", "Validation"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                (
                    "etat_intervention",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "date_action",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("metadata", models.JSONField(blank=True, null=True)),
                (
                    "intervention",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="maintenance.intervention",
                    ),
                ),
                (
                    "machine",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="maintenance.machine",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "workorder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="maintenance.workorder",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="intervention",
            name="workorder",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="interventions",
                to="maintenance.workorder",
            ),
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "Créer"),
                            ("update", "Modifier"),
                            ("delete", "Supprimer"),
                            ("validate", "Valider"),
                            ("start", "Démarrer"),
                            ("finish", "Términer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("model", models.CharField(max_length=100)),
                ("object_id", models.IntegerField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("user_agent", models.TextField(blank=True, null=True)),
                ("endpoint", models.CharField(blank=True, max_length=255, null=True)),
                ("method", models.CharField(blank=True, max_length=10, null=True)),
                ("changements", models.JSONField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="categorie",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="utilisateurs",
                to="maintenance.categorie",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="groups",
            field=models.ManyToManyField(
                blank=True,
                help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                related_name="user_set",
                related_query_name="user",
                to="auth.group",
                verbose_name="groups",
            ),
        ),
        migrations.AddField(
            model_name="utilisateur",
            name="user_permissions",
            field=models.ManyToManyField(
                blank=True,
                help_text="Specific permissions for this user.",
                related_name="user_set",
                related_query_name="user",
                to="auth.permission",
                verbose_name="user permissions",
            ),
        ),
    ]
