# Generated by Django 4.2.7 on 2026-04-12 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="utilisateur",
            name="role",
            field=models.CharField(
                choices=[
                    ("admin", "Admin"),
                    ("technicien", "Technicien"),
                    ("expert", "Expert"),
                    ("operateur", "Operateur"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
