# Generated by Django 4.2.7 on 2026-04-14 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0002_alter_utilisateur_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="categorie",
            name="nom",
            field=models.CharField(
                blank=True,
                choices=[
                    ("electrique", "Électrique"),
                    ("mecanique", "Mécanique"),
                    ("automation", "Automation"),
                    ("utilitaire", "Utilitaire"),
                ],
                max_length=50,
                unique=True,
            ),
        ),
    ]
