# Generated by Django 4.2.7 on 2026-06-08 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0003_alter_categorie_nom"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="activation_token",
            field=models.CharField(blank=True, max_length=64, null=True, unique=True),
        ),
    ]
