# Generated by Django 4.2.7 on 2026-06-09 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0004_utilisateur_activation_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="utilisateur",
            name="temporary_password",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
