# Generated by Django 4.2.7 on 2026-06-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0007_passwordresetrequest_processed_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="pieceutilisee",
            name="etat",
            field=models.CharField(
                choices=[("reservee", "Réservée"), ("consommee", "Consommée")],
                default="reservee",
            ),
        ),
    ]
