# Generated by Django 4.2.7 on 2026-06-11 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0008_pieceutilisee_etat"),
    ]

    operations = [
        migrations.AddField(
            model_name="piece",
            name="prix_unitaire",
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10),
        ),
    ]
