# Generated by Django 4.2.7 on 2026-06-20 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("maintenance", "0009_piece_prix_unitaire"),
    ]

    operations = [
        migrations.AddField(
            model_name="machine",
            name="latitude",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="machine",
            name="longitude",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
